# Generated by Django 4.0 on 2023-06-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(max_length=20)),
            ],
        ),
    ]
